// "use client";

// import { ResourceState } from "@/utils/types/resource";
// import { useClerk, useUser } from "@clerk/nextjs";
// import React, { createContext, useContext } from "react";

// const initialState: ResourceState = {
//   id: "",
//   userId: "",

//   name: "",
//   slug: "",
//   tagline: "",
//   description: "",

//   website: "",
//   documentationUrl: "",
//   githubUrl: "",

//   category: "",
//   pricing: "free",

//   tags: [],
//   useCases: [],
//   alternatives: [],

//   platforms: [],
//   license: "",

//   logo: "",
//   screenshots: [],

//   headquarters: "",
//   country: "",

//   communityRating: {
//     average: 0,
//     count: 0,
//   },

//   githubStats: {
//     stars: 0,
//     forks: 0,
//     issues: 0,
//     lastCommitDate: null,
//     repository: "",
//   },

//   comparisonTargets: [],
//   stackFit: {
//     frontend: false,
//     backend: false,
//     database: false,
//     auth: false,
//     deployment: false,
//     testing: false,
//     ai: false,
//   },

//   developerEvents: [],

//   featured: false,
//   published: false,

//   createdAt: "",
//   updatedAt: "",
// };

// interface ResourceContextType {
//   resource: ResourceState;
//   setResource: React.Dispatch<React.SetStateAction<ResourceState>>;
//   loading: boolean;
//   setLoading: React.Dispatch<React.SetStateAction<boolean>>;
//   isHydrated: boolean;
//   handleChange: (
//     e: React.ChangeEvent<
//       HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
//     >,
//   ) => void;
//   handleSubmit: (e: React.FormEvent) => Promise<void>;
// }

// const ResourceContext = createContext<ResourceContextType | undefined>(
//   undefined,
// );

// const commaSeparatedToArray = (value: string) =>
//   value
//     .split(",")
//     .map((item) => item.trim())
//     .filter(Boolean);

// const slugify = (value: string) =>
//   value
//     .toLowerCase()
//     .trim()
//     .replace(/['"]/g, "")
//     .replace(/[^a-z0-9]+/g, "-")
//     .replace(/^-+|-+$/g, "");

// export const ResourceProvider: React.FC<{ children: React.ReactNode }> = ({
//   children,
// }) => {
//   const [resource, setResource] = React.useState<ResourceState>(initialState);
//   const [loading, setLoading] = React.useState(false);
//   const [isHydrated, setIsHydrated] = React.useState(false);

//   const { openSignIn } = useClerk();
//   const { isSignedIn } = useUser();

//   React.useEffect(() => {
//     const savedResource = localStorage.getItem("resource");

//     if (savedResource) {
//       try {
//         const parsed = JSON.parse(savedResource);

//         setResource({
//           ...initialState,
//           ...parsed,
//           tags: Array.isArray(parsed.tags) ? parsed.tags : [],
//           useCases: Array.isArray(parsed.useCases) ? parsed.useCases : [],
//           alternatives: Array.isArray(parsed.alternatives)
//             ? parsed.alternatives
//             : [],
//           platforms: Array.isArray(parsed.platforms) ? parsed.platforms : [],
//           screenshots: Array.isArray(parsed.screenshots)
//             ? parsed.screenshots
//             : [],
//           comparisonTargets: Array.isArray(parsed.comparisonTargets)
//             ? parsed.comparisonTargets
//             : [],
//           developerEvents: Array.isArray(parsed.developerEvents)
//             ? parsed.developerEvents
//             : [],
//         });
//       } catch {
//         setResource(initialState);
//       }
//     }

//     setIsHydrated(true);
//   }, []);

//   React.useEffect(() => {
//     if (!isHydrated) return;
//     localStorage.setItem("resource", JSON.stringify(resource));
//   }, [resource, isHydrated]);

//   const handleChange = (
//     e: React.ChangeEvent<
//       HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
//     >,
//   ) => {
//     const { name, value } = e.target;

//     setResource((prev) => {
//       let updatedFieldValue: string | string[] = value;

//       if (name === "tags" || name === "alternatives" || name === "useCases") {
//         updatedFieldValue = commaSeparatedToArray(value);
//       }

//       const updatedResource: ResourceState = {
//         ...prev,
//         [name]: updatedFieldValue,
//         updatedAt: new Date().toISOString(),
//       };

//       if (name === "name") {
//         const previousAutoSlug = slugify(prev.name);
//         const nextAutoSlug = slugify(value);

//         const slugWasEmpty = !prev.slug;
//         const slugWasAutoGenerated = prev.slug === previousAutoSlug;

//         if (slugWasEmpty || slugWasAutoGenerated) {
//           updatedResource.slug = nextAutoSlug;
//         }
//       }

//       return updatedResource;
//     });
//   };

//   const handleSubmit = async (e: React.FormEvent) => {
//     e.preventDefault();

//     if (loading) return;

//     if (!isSignedIn) {
//       openSignIn();
//       return;
//     }

//     try {
//       setLoading(true);

//       // Replace this with your real save action / API call
//       await new Promise((resolve) => setTimeout(resolve, 1500));

//       alert("Resource saved");
//     } catch (error) {
//       console.error("Failed to save resource:", error);
//       alert("Something went wrong while saving the resource.");
//     } finally {
//       setLoading(false);
//     }
//   };

//   return (
//     <ResourceContext.Provider
//       value={{
//         resource,
//         setResource,
//         loading,
//         setLoading,
//         isHydrated,
//         handleChange,
//         handleSubmit,
//       }}
//     >
//       {children}
//     </ResourceContext.Provider>
//   );
// };

// export const useResource = () => {
//   const context = useContext(ResourceContext);

//   if (!context) {
//     throw new Error("useResource must be used within a ResourceProvider");
//   }

//   return context;
// };

"use client";

import {
  defaultResourceFormState,
  type ResourceFormState,
} from "@/utils/types/resource";
import {
  normalizeResourceFormState,
  validateResourceFormState,
  validateResourceInput,
} from "@/lib/validators/resource";
import { useClerk, useUser } from "@clerk/nextjs";
import React, { createContext, useContext } from "react";

interface ResourceContextType {
  resource: ResourceFormState;
  setResource: React.Dispatch<React.SetStateAction<ResourceFormState>>;
  loading: boolean;
  setLoading: React.Dispatch<React.SetStateAction<boolean>>;
  isHydrated: boolean;
  handleChange: (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
    >,
  ) => void;
  handleSubmit: (e: React.FormEvent<HTMLFormElement>) => Promise<void>;
}

const ResourceContext = createContext<ResourceContextType | undefined>(
  undefined,
);

const commaSeparatedToArray = (value: string) =>
  value
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);

const slugify = (value: string) =>
  value
    .toLowerCase()
    .trim()
    .replace(/['"]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

export const ResourceProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [resource, setResource] = React.useState<ResourceFormState>(
    defaultResourceFormState,
  );
  const [loading, setLoading] = React.useState(false);
  const [isHydrated, setIsHydrated] = React.useState(false);

  const { openSignIn } = useClerk();
  const { isSignedIn, user } = useUser();

  React.useEffect(() => {
    const savedResource = localStorage.getItem("resource");

    if (savedResource) {
      try {
        const parsed = JSON.parse(savedResource);

        setResource({
          ...defaultResourceFormState,
          ...parsed,
          tags: Array.isArray(parsed.tags)
            ? parsed.tags.join(", ")
            : (parsed.tags ?? ""),
          useCases: Array.isArray(parsed.useCases)
            ? parsed.useCases.join(", ")
            : (parsed.useCases ?? ""),
          alternatives: Array.isArray(parsed.alternatives)
            ? parsed.alternatives.join(", ")
            : (parsed.alternatives ?? ""),
          platforms: Array.isArray(parsed.platforms)
            ? parsed.platforms.join(", ")
            : (parsed.platforms ?? ""),
          screenshots: Array.isArray(parsed.screenshots)
            ? parsed.screenshots.join(", ")
            : (parsed.screenshots ?? ""),
          comparisonTargets: Array.isArray(parsed.comparisonTargets)
            ? parsed.comparisonTargets
            : [],
          developerEvents: Array.isArray(parsed.developerEvents)
            ? parsed.developerEvents
            : [],
          communityRating: parsed.communityRating ?? {
            average: 0,
            count: 0,
          },
          githubStats: parsed.githubStats ?? {
            stars: 0,
            forks: 0,
            issues: 0,
            lastCommitDate: null,
            repository: "",
          },
          stackFit: {
            ...defaultResourceFormState.stackFit,
            ...(parsed.stackFit ?? {}),
          },
        });
      } catch {
        setResource(defaultResourceFormState);
      }
    }

    setIsHydrated(true);
  }, []);

  React.useEffect(() => {
    if (!isHydrated) return;
    localStorage.setItem("resource", JSON.stringify(resource));
  }, [resource, isHydrated]);

  const handleChange = (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
    >,
  ) => {
    const { name, value } = e.target;

    setResource((prev) => {
      const updatedResource: ResourceFormState = {
        ...prev,
        [name]: value,
      };

      if (name === "name") {
        const previousAutoSlug = slugify(prev.name);
        const nextAutoSlug = slugify(value);

        const slugWasEmpty = !prev.slug;
        const slugWasAutoGenerated = prev.slug === previousAutoSlug;

        if (slugWasEmpty || slugWasAutoGenerated) {
          updatedResource.slug = nextAutoSlug;
        }
      }

      return updatedResource;
    });
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    if (loading) return;

    if (!isSignedIn) {
      openSignIn();
      return;
    }

    try {
      setLoading(true);

      const formValidation = validateResourceFormState(resource);

      if (!formValidation.success) {
        console.error("Form validation failed:", formValidation.error.issues);

        alert("Please correct the form fields before submitting.");
        return;
      }

      const normalizedResource = normalizeResourceFormState(resource);

      const inputValidation = validateResourceInput(normalizedResource);

      if (!inputValidation.success) {
        console.error(
          "Normalized input validation failed:",
          inputValidation.error.issues,
        );
        alert("The resource data is invalid after normalization.");
        return;
      }

      const payload = {
        ...inputValidation.data,
        userId: user?.id ?? "",
      };

      console.log("Validated resource payload:", payload);

      // Replace this with your real save action / API call
      await new Promise((resolve) => setTimeout(resolve, 1500));

      alert("Resource saved");
    } catch (error) {
      console.error("Failed to save resource:", error);
      alert("Something went wrong while saving the resource.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <ResourceContext.Provider
      value={{
        resource,
        setResource,
        loading,
        setLoading,
        isHydrated,
        handleChange,
        handleSubmit,
      }}
    >
      {children}
    </ResourceContext.Provider>
  );
};

export const useResource = () => {
  const context = useContext(ResourceContext);

  if (!context) {
    throw new Error("useResource must be used within a ResourceProvider");
  }

  return context;
};
