"use client";

import {
  defaultResourceFormState,
  type ResourceFormState,
  type Resource,
} from "@/utils/types/resource";
import {
  normalizeResourceFormState,
  validateResourceFormState,
  validateResourceInput,
} from "@/lib/validators/resource";
import { useClerk, useUser } from "@clerk/nextjs";
import React, { createContext, useContext } from "react";
import {
  saveResourceToDB,
  getResourceFromDB,
  getUserResourcesFromDB,
} from "@/app/actions/resource";
import toast from "react-hot-toast";
import { useRouter, usePathname } from "next/navigation";

interface ResourceContextType {
  resource: ResourceFormState;
  setResource: React.Dispatch<React.SetStateAction<ResourceFormState>>;
  loading: boolean;
  setLoading: React.Dispatch<React.SetStateAction<boolean>>;
  isHydrated: boolean;
  handleChange: (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
    >,
  ) => void;
  handleSubmit: (e: React.FormEvent<HTMLFormElement>) => Promise<void>;
  resources: Resource[];
  setResources: React.Dispatch<React.SetStateAction<Resource[]>>;
}

const ResourceContext = createContext<ResourceContextType | undefined>(
  undefined,
);

const slugify = (value: string) =>
  value
    .toLowerCase()
    .trim()
    .replace(/['"]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

export const ResourceProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [resource, setResource] = React.useState<ResourceFormState>(
    defaultResourceFormState,
  );
  const [loading, setLoading] = React.useState(false);
  const [isHydrated, setIsHydrated] = React.useState(false);
  const [resources, setResources] = React.useState<Resource[]>([]);

  const { openSignIn } = useClerk();
  const { isSignedIn } = useUser();

  const router = useRouter();
  const pathname = usePathname();

  const isDashboardPage = pathname === "/dashboard";

  React.useEffect(() => {
    const savedResource = localStorage.getItem("resource");

    if (savedResource) {
      try {
        const parsed = JSON.parse(savedResource);

        setResource({
          ...defaultResourceFormState,
          ...parsed,
          tags: Array.isArray(parsed.tags)
            ? parsed.tags.join(", ")
            : (parsed.tags ?? ""),
          useCases: Array.isArray(parsed.useCases)
            ? parsed.useCases.join(", ")
            : (parsed.useCases ?? ""),
          alternatives: Array.isArray(parsed.alternatives)
            ? parsed.alternatives.join(", ")
            : (parsed.alternatives ?? ""),
          platforms: Array.isArray(parsed.platforms)
            ? parsed.platforms.join(", ")
            : (parsed.platforms ?? ""),
          screenshots: Array.isArray(parsed.screenshots)
            ? parsed.screenshots.join(", ")
            : (parsed.screenshots ?? ""),
          comparisonTargets: Array.isArray(parsed.comparisonTargets)
            ? parsed.comparisonTargets
            : [],
          developerEvents: Array.isArray(parsed.developerEvents)
            ? parsed.developerEvents
            : [],
          communityRating: parsed.communityRating ?? {
            average: 0,
            count: 0,
          },
          githubStats: parsed.githubStats ?? {
            stars: 0,
            forks: 0,
            issues: 0,
            lastCommitDate: null,
            repository: "",
          },
          stackFit: {
            ...defaultResourceFormState.stackFit,
            ...(parsed.stackFit ?? {}),
          },
        });
      } catch {
        setResource(defaultResourceFormState);
      }
    }

    setIsHydrated(true);
  }, []);

  React.useEffect(() => {
    if (!isHydrated) return;
    localStorage.setItem("resource", JSON.stringify(resource));
  }, [resource, isHydrated]);

  React.useEffect(() => {
    if (isDashboardPage) {
      getUserResources();
    }
  }, [isDashboardPage]);

  const handleChange = (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
    >,
  ) => {
    const { name, value } = e.target;

    setResource((prev) => {
      const updatedResource: ResourceFormState = {
        ...prev,
        [name]: value,
      };

      if (name === "name") {
        const previousAutoSlug = slugify(prev.name);
        const nextAutoSlug = slugify(value);

        const slugWasEmpty = !prev.slug;
        const slugWasAutoGenerated = prev.slug === previousAutoSlug;

        if (slugWasEmpty || slugWasAutoGenerated) {
          updatedResource.slug = nextAutoSlug;
        }
      }

      return updatedResource;
    });
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    if (loading) return;

    if (!isSignedIn) {
      toast.error("Please sign in to add a resource.");
      openSignIn();
      return;
    }

    try {
      setLoading(true);

      const formValidation = validateResourceFormState(resource);

      if (!formValidation.success) {
        console.error("Form validation failed:", formValidation.error.issues);
        toast.error("Please correct the form fields before submitting.");
        return;
      }

      const normalizedResource = normalizeResourceFormState(resource);

      const inputValidation = validateResourceInput(normalizedResource);

      if (!inputValidation.success) {
        console.error(
          "Normalized input validation failed:",
          inputValidation.error.issues,
        );
        toast.error("The resource data is invalid after normalization.");
        return;
      }

      const payload = inputValidation.data;

      console.log("Validated resource payload:", payload);

      const toastId = toast.loading("Saving resource...");

      const savedResource = await saveResourceToDB(payload);

      toast.success("🎉 Resource saved successfully!", { id: toastId });

      setResource(defaultResourceFormState);
      localStorage.removeItem("resource");
      router.push(`/dashboard/resource/edit/${savedResource.slug}`);
    } catch (error) {
      console.error("❌ Failed to save resource:", error);
      toast.error("Something went wrong while saving the resource.");
    } finally {
      setLoading(false);
    }
  };

  const getUserResources = async () => {
    setLoading(true);

    try {
      const userResources = await getUserResourcesFromDB();
      setResources(userResources);
    } catch (error) {
      console.error("❌ Failed to fetch user resources:", error);
      toast.error("Something went wrong while fetching your resources.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <ResourceContext.Provider
      value={{
        resource,
        setResource,
        loading,
        setLoading,
        isHydrated,
        handleChange,
        handleSubmit,
        resources,
        setResources,
      }}
    >
      {children}
    </ResourceContext.Provider>
  );
};

export const useResource = () => {
  const context = useContext(ResourceContext);

  if (!context) {
    throw new Error("useResource must be used within a ResourceProvider");
  }

  return context;
};
